module.exports = {
  constants: 'src/constants',
  components: 'src/components',
  i18nResource: 'src/i18nResource',
  iconResource: 'src/iconResource',
  utils: 'src/utils',
  pages: 'src/pages',
  services: 'src/services',
  types: 'src/types',
  __tests__: 'src/__tests__',
  styles: 'src/styles',
  mock: 'src/mock',
  idl: 'src/idl',
  dingtalkRpc: 'src/services/dingtalkRpc',
  vscode: 'vscode',
}
