module EduAlbum;

struct StudentStructure {
  1: string userId;
  2: string nick;
}

struct ILwpFaceFacadeResult {
  1: boolean hasFace;
  2: boolean signed;
  3: boolean useAIFaceDetect;
  4: string albumSavePage;
  5: string albumPersonalPage;
  6: string albumMiniAppId;
  7: list<StudentStructure> students;
}

struct ILwpFaceFacadeModel {
  1: boolean success;
  2: string errorMsg;
  3: string errorCode;
  4: ILwpFaceFacadeResult result;
}
